# Generated by Django 5.2.7 on 2025-11-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image to use instead of SVG icon.', null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon_svg',
            field=models.TextField(blank=True, help_text="SVG path element (the 'd' attribute value)", null=True),
        ),
    ]
